baseURL = "https://area44.github.io/hugo-spotless"
languageCode = "en-us"
title = "Spotless"
description = "Hugo Spotless is a hugo template built with Bootstrap 5"
theme = "hugo-spotless"
relativeURLs = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "HOME"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "ABOUT"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "posts"
    name = "POST"
    url = "/posts/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "CONTACT"
    url = "/contact/"
    weight = 4